apiVersion: v1
kind: ConfigMap
metadata:
  name: backend
  namespace: expense
data:
  DB_HOST: mysql

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  labels:
    tier: backend
    project: expense
spec:
  replicas: {{.Values.deployment.replicas}}
  selector:
    matchLabels:
      tier: backend
      project: expense
  template:
    metadata:
      labels:
        tier: backend
        project: expense
    spec:
      containers:
      - name: backend
        image: docksterharsha/backend:{{.Values.deployment.imageVersion}}
        ports:
        - containerPort: {{.Values.configmap.backend_port}}
        envFrom:
        - configMapRef:
            name: backend

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: expense
spec:
  selector:
    tier: backend
    project: expense
  ports:
    - protocol: TCP
      port: {{.Values.configmap.backend_port}}
      targetPort: {{.Values.configmap.backend_port}}
