apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: expense-cluster-reader
  namespace: expense
rules:
- apiGroups: [""]
  resources: ["secrets", "persistentvolumes", "nodes"]
  verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: expense-cluster-reader
  namespace: expense
subjects:
- kind: User
  name: harish
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: expense-cluster-reader
  apiGroup: rbac.authorization.k8s.io
