apiVersion: v1
kind: ConfigMap
metadata:
  name: backend
  namespace: expense
data:
  DB_HOST: mysql

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  labels:
    tier: backend
    project: expense
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: backend
      project: expense
  template:
    metadata:
      labels:
        tier: backend
        project: expense
    spec:
      containers:
      - name: backend
        image: docksterharsha/backend:1.0
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: backend

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: expense
spec:
  selector:
    tier: backend
    project: expense
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
