apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: expense
  labels:
    tier: db
    project: expense
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: db
      project: expense
  template:
    metadata:
      labels:
        tier: db
        project: expense
    spec:
      containers:
      - name: mysql
        image: docksterharsha/mysql:1.0
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql
        persistentVolumeClaim:
          claimName: mysql-pvc
      nodeSelector:
        topology.kubernetes.io/zone: us-east-1b

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: expense
spec:
  selector:
    tier: db
    project: expense
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
