apiVersion: v1
kind: Pod
metadata:
  name: nodeport-pod
  labels:
    project: expense
    environment: dev
spec:
  containers:
  - name: nginx
    image: nginx
    command: ['sh', '-c', 'echo "Hello from Kubernetes" > /usr/share/nginx/html/index.html']

---

apiVersion: v1
kind: Service
metadata:
  name: nodeport-service
spec:
  type: NodePort
  selector:
    project: expense
    environment: dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32760
