kind: Pod
apiVersion: v1
metadata:
  name: uni-pod
  namespace: expense
  labels:
    project: expense
    environment: dev
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80

