apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  labels:
    tier: app1
    purpose: ingress
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: app1
      purpose: ingress
  template:
    metadata:
      labels:
        tier: app1
        purpose: ingress
    spec:
      containers:
      - name: app1
        image: joindevops/app1:1.0

---
apiVersion: v1
kind: Service
metadata:
  name: app1
spec:
  selector:
    tier: app1
    purpose: ingress
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app1
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/tags: Environment=dev,Team=test
    alb.ingress.kubernetes.io/group.name: joindevops
spec:
  ingressClassName: alb
  rules:
  - host: "app1.daws78s.online"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app1
            port:
              number: 80
