apiVersion: apps/v1
kind: Namespace
metadata:
  name: expense

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: expense
  labels:
    tier: db
    project: expense
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: db
      project: expense
  template:
    metadata:
      labels:
        tier: db
        project: expense
    spec:
      containers:
      - name: mysql
        image: docksterharsha/mysql:1.0
        ports:
        - containerPort: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: expense
spec:
  selector:
    tier: db
    project: expense
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
