apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-deployment
  labels:
    project: expense
    environment: dev
    component: deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      project: expense
      environment: dev
      component: pod
  template:
    metadata:
      labels:
        project: expense
        environment: dev
        component: pod
    spec:
      containers:
      - name: nginx
        image: nginx
