apiVersion: v1
kind: Service
metadata:
  name: mysql-headless
  namespace: expense
  labels:
    tier: db
    project: expense
spec:
  clusterIP: None
  ports:
  - port: {{.Values.configmap.port}}
    targetPort: {{.Values.configmap.port}}
  selector:
    tier: db
    project: expense

---

apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: expense
  labels:
    tier: db
    project: expense
spec:
  ports:
  - port: {{.Values.configmap.port}}
    targetPort: {{.Values.configmap.port}}
  selector:
    tier: db
    project: expense

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: expense
spec:
  selector:
    matchLabels:
      tier: db
      project: expense
  serviceName: "mysql-headless"
  replicas: {{.Values.deployment.replicas}}
  template:
    metadata:
      labels:
        tier: db
        project: expense
    spec:
      containers:
      - name: mysql
        image: docksterharsha/mysql:{{.Values.deployment.imageVersion}}
        ports:
        - containerPort: {{.Values.configmap.port}}
        volumeMounts:
        - name: mysql
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "mysql-sc-2"
      resources:
        requests:
          storage: 5Gi