apiVersion: v1
kind: Pod
metadata:
  name: with-pod-affinity
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: purpose
            operator: In
            values:
            - affinity
        topologyKey: topology.kubernetes.io/zone
  containers:
  - name: with-pod-affinity
    image: nginx

---
apiVersion: v1
kind: Pod
metadata:
  name: with-pod-anti-affinity
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: purpose
              operator: In
              values:
              - affinity
          topologyKey: topology.kubernetes.io/zone
  containers:
  - name: with-pod-anti-affinity
    image: nginx
